[package]
name = "DIALer"
version = "0.0.2"
authors = ["cullinan"]
edition = '2021'

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.6"
reqwest = { version = "0.11", features = ["blocking"] }
